
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.lang.*;
import java.sql.PreparedStatement;
import java.sql.SQLException;
   import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Booking extends javax.swing.JFrame {

      String url = "jdbc:mysql://localhost:3306/Airline";
        String user = "root";
        String databasepassword = "";
        
        private String time;
    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
    }
    
    
    
    public int getRandomNumber(){
        // Create a Random object
        Random random = new Random();

        // Generate a random integer
        int randomNumber = random.nextInt(8000);

        // Print the random number
        return randomNumber;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tLastName = new javax.swing.JTextField();
        tPhoneNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tAddress = new javax.swing.JTextField();
        tId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSex = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPay = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDestination = new javax.swing.JComboBox<>();
        jFlightNumber = new javax.swing.JComboBox<>();
        jClass = new javax.swing.JComboBox<>();
        jClass1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPayment = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        tArrivalTime = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tBasePrice = new javax.swing.JTextField();
        tAvailableSeats = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tDepatureTime = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        dsfgds = new javax.swing.JLabel();
        tAmount = new javax.swing.JTextField();
        tStatus = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booking");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204,0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("First Name");

        tFirstName.setBackground(new java.awt.Color(255, 255, 255));
        tFirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tFirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Last Name");

        tLastName.setBackground(new java.awt.Color(255, 255, 255));
        tLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tLastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        tPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        tPhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tPhoneNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Phone Number");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Email");

        tEmail.setBackground(new java.awt.Color(255, 255, 255));
        tEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Address");

        tAddress.setBackground(new java.awt.Color(255, 255, 255));
        tAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        tId.setBackground(new java.awt.Color(255, 255, 255));
        tId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Id Number");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Sex");

        jSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "VISA Credit/Debit card" }));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Payement Method");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSex, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPay, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Thibus29STru", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Booking");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 300, 60));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Enter customer Details ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 280, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204,0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Destination");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 42, 130, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Flight Number");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 86, 130, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 185, 130, 30));

        jDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Destination", "India", "USA", "Australia", "Canada" }));
        jDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDestinationActionPerformed(evt);
            }
        });
        jPanel2.add(jDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 45, 240, -1));

        jFlightNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFlightNumberActionPerformed(evt);
            }
        });
        jPanel2.add(jFlightNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 89, 240, -1));

        jClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose the Class", "First Class", "Bussiness Class", "Economy Class" }));
        jClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClassActionPerformed(evt);
            }
        });
        jPanel2.add(jClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 137, 240, -1));

        jClass1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Class", "Bussiness Class", "Economy Class" }));
        jPanel2.add(jClass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 137, 240, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Class");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 137, 130, 30));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Payment Status");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 30));

        jPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select payment Status", "Paid", "Not paid" }));
        jPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(jPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 240, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 469, 240));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Choose Destinations and Flight");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 280, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 120, 110));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 180, 50));

        tArrivalTime.setEditable(false);
        tArrivalTime.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        tArrivalTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tArrivalTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 130, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Flight Arrival time");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 120, 40));

        tBasePrice.setEditable(false);
        tBasePrice.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        tBasePrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tBasePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 150, 40));

        tAvailableSeats.setEditable(false);
        tAvailableSeats.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        tAvailableSeats.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tAvailableSeats, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 130, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Available Seats");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 120, 40));

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jButton5.setText("Continue");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 210, 50));

        jTextField2.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 130, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Flight Arrival time");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 120, 40));

        jLabel24.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Base Price");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 120, 40));

        jTextField12.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 130, 40));

        jTextField13.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 130, 40));

        jLabel25.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Available Seats");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 120, 40));

        tDepatureTime.setEditable(false);
        tDepatureTime.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        tDepatureTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tDepatureTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 130, 40));

        jLabel26.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Departure Time");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 120, 40));

        dsfgds.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        dsfgds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dsfgds.setText("Total Amount");
        getContentPane().add(dsfgds, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 140, 40));

        tAmount.setEditable(false);
        tAmount.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        tAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 130, 40));

        tStatus.setEditable(false);
        tStatus.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        tStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, 130, 40));

        jLabel28.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Status");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 120, 40));

        setSize(new java.awt.Dimension(1052, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tFirstName.setText("");
        tLastName.setText("");
        tEmail.setText("");
        tPhoneNumber.setText("");
        tId.setText("");
        tAddress.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         int YesNo = JOptionPane.showConfirmDialog(this,"Do you Want to Exit?","Exit",JOptionPane.YES_NO_OPTION);
         
         if(YesNo== JOptionPane.YES_OPTION){
             new Mainmenu().setVisible(true);
             this.dispose();
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int YesNo = JOptionPane.showConfirmDialog(this,"Are you sure?","Book",JOptionPane.YES_NO_OPTION);
        String status = tStatus.getText();
        
        
        String FirstName = tFirstName.getText();
        String LastName = tLastName.getText();
        String Email = tEmail.getText();
        String PhoneNumber = tPhoneNumber.getText();
        String Id = tId.getText();
        String Address = tAddress.getText();
        String sex = jSex.getSelectedItem().toString();
        String payment = jPay.getSelectedItem().toString();
        String paid = jPayment.getSelectedItem().toString();
        String amount = tAmount.getText();
        String destination = jDestination.getSelectedItem().toString();
            
        String flightNumber = jFlightNumber.getSelectedItem().toString();
        String className = jClass.getSelectedItem().toString();
        String TicketId = "A" + String.valueOf(getRandomNumber());

        boolean success = false;
        if(status.equals("Available") && !(FirstName.equals("") || LastName.equals("") ||  Email.equals("") || PhoneNumber.equals("") || Id.equals("") || Address.equals("") )){
            success = true;
        }
        
        else if(status.equals("Not Available")){
           JOptionPane.showMessageDialog(rootPane, "Payment should be Successfull");
            
        }
        else{
             JOptionPane.showMessageDialog(rootPane, "Please fill all Fields");
        }
        
   
         if(YesNo== JOptionPane.YES_OPTION && success ==true){
          
             
            String sql = "insert into customer (FirstName,LastName,email,PhoneNumber,Address,IdNumber,Sex) values(?,?,?,?,?,?,?)" ;
            try (Connection conn = DriverManager.getConnection(url, user, databasepassword);
                 PreparedStatement pstmt = conn.prepareStatement(sql)) {

                pstmt.setString(1, FirstName);
                pstmt.setString(2, LastName);
                pstmt.setString(3,Email);
                pstmt.setString(4,PhoneNumber);
                pstmt.setString(5,Address);
                pstmt.setString(6,Id); 
                pstmt.setString(7,sex);
                
                pstmt.executeUpdate();

            } catch (SQLException e) {
                System.out.println("Error updating record: " + e.getMessage());
            }
            
            
            
              String sql3 = "insert into payment(CustomerId,TicketId,PayementMethod,PaidAmount,payementStatus) values(?,?,?,?,?)" ;
            try (Connection conn = DriverManager.getConnection(url, user, databasepassword);
                    PreparedStatement pstmt3 = conn.prepareStatement(sql3)) {
                    pstmt3.setString(1, Id);
                    pstmt3.setString(2, TicketId);
                    pstmt3.setString(3,payment);
                    pstmt3.setString(4,amount);
                    pstmt3.setString(5,paid);   
                pstmt3.executeUpdate();

            } catch (SQLException e) {
                System.out.println("Error updating record: " + e.getMessage());
            }
      
            
            String sql4 = "insert into Ticket(TicketId,IDNumber,FlightNumber,Destination,Status) values(?,?,?,?,?)" ;
            try (Connection conn = DriverManager.getConnection(url, user, databasepassword);
                    PreparedStatement pstmt4 = conn.prepareStatement(sql4)) {
                    pstmt4.setString(1, TicketId);
                    pstmt4.setString(2, Id);
                    pstmt4.setString(3, flightNumber);
                    pstmt4.setString(4, destination);
                    pstmt4.setString(5,"Ticket is Issued");
                   
                pstmt4.executeUpdate();

            } catch (SQLException e) {
                System.out.println("Error updating record: " + e.getMessage());
            }
            
            
     
                 String sql2 = "insert into book (FlightNumber,ClassName,TicketId,CustomerId) values(?,?,?,?)" ;
            try (Connection conn = DriverManager.getConnection(url, user, databasepassword);
                 PreparedStatement pstmt2 = conn.prepareStatement(sql2)) {

                pstmt2.setString(1, flightNumber);
                pstmt2.setString(2, className);
                pstmt2.setString(3,TicketId);
                pstmt2.setString(4,Id);
 
                
                pstmt2.executeUpdate();

                JOptionPane.showMessageDialog(rootPane,"Booking Successfull");
                
            String time = tDepatureTime.getText();
             
             TicketReciept ticket = new TicketReciept();
             ticket.setDetails(FirstName,LastName,time,flightNumber,className,TicketId,destination);
             
             Mainmenu mainmenu = new Mainmenu();
             mainmenu.setVisible(true);
               this.dispose();

            } catch (SQLException e) {
                System.out.println("Error updating record: " + e.getMessage());
            }
      
           

         }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPaymentActionPerformed
        // TODO add your handling code here:
        String pay = jPayment.getSelectedItem().toString();
        if(pay.equals("Paid")){
            tStatus.setText("Available");
        }
        else{
            tStatus.setText("Not Available");
        }
        
        
    }//GEN-LAST:event_jPaymentActionPerformed

    private void jClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClassActionPerformed
        // TODO add your handling code here:
        char classname = jClass.getSelectedItem().toString().charAt(0);
        String FlightNumber = jFlightNumber.getSelectedItem().toString();

        String query1 = "SELECT * FROM flightclass WHERE FlightNumber = '" + FlightNumber + "' AND ClassName LIKE '" + classname + "%'";
        String query2 = "SELECT * from flight where FlightNumber = '" + FlightNumber + "' ";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, user, databasepassword);

            Statement statement = connection.createStatement();
            ResultSet result1 = statement.executeQuery(query1);

            while(result1.next()) { // Check if there's a matching record
                tBasePrice.setText("Rs." + result1.getString(2));
                double total = Double.parseDouble(result1.getString(2)) + 35000;
                tAmount.setText("Rs." + total );
                String NumberOfSeats = result1.getString(3);
                tAvailableSeats.setText(NumberOfSeats);
            

            }

            ResultSet result2 = statement.executeQuery(query2);

            while(result2.next()) { // Check if there's a matching record
                tArrivalTime.setText(result2.getString(2));
                tDepatureTime.setText(result2.getString(3));
                
                

            }

            connection.close();

        } catch (Exception e) {
            System.out.println(e);

        }

    }//GEN-LAST:event_jClassActionPerformed

    private void jFlightNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFlightNumberActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jFlightNumberActionPerformed

    private void jDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDestinationActionPerformed
        // TODO add your handling code here:
        jFlightNumber.removeAllItems();

        String destination = jDestination.getSelectedItem().toString();

        String query = "SELECT flightNumber FROM flight WHERE destination = '" + destination + "'";

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, user, databasepassword);

            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery(query);

            while (result.next()) {
                String flightNumber = result.getString("flightNumber");
                jFlightNumber.addItem(flightNumber);
            }
            connection.close();

        } catch (Exception e) {
            System.out.println(e);

        }

    }//GEN-LAST:event_jDestinationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dsfgds;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jClass;
    private javax.swing.JComboBox<String> jClass1;
    private javax.swing.JComboBox<String> jDestination;
    private javax.swing.JComboBox<String> jFlightNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jPay;
    private javax.swing.JComboBox<String> jPayment;
    private javax.swing.JComboBox<String> jSex;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField tAddress;
    private javax.swing.JTextField tAmount;
    private javax.swing.JTextField tArrivalTime;
    private javax.swing.JTextField tAvailableSeats;
    private javax.swing.JTextField tBasePrice;
    private javax.swing.JTextField tDepatureTime;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tFirstName;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tLastName;
    private javax.swing.JTextField tPhoneNumber;
    private javax.swing.JTextField tStatus;
    // End of variables declaration//GEN-END:variables
}
