
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Register extends javax.swing.JFrame {

    
    
        private String EmpId,password;
       String url = "jdbc:mysql://localhost:3306/Airline";
        String user = "root";
        String databasepassword = "";
        
          private String available = "yes";
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tLastName = new javax.swing.JTextField();
        tFirstName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        tEmployeeId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tPassword = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        checkbox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        tRPassword = new javax.swing.JPasswordField();
        tREmployeeId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register New User");
        setResizable(false);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Last Name");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 138, 40));

        tLastName.setBackground(new java.awt.Color(255, 255, 255));
        tLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tLastName.setForeground(new java.awt.Color(0, 0, 0));
        tLastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tLastName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel2.add(tLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 230, 38));

        tFirstName.setBackground(new java.awt.Color(255, 255, 255));
        tFirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tFirstName.setForeground(new java.awt.Color(0, 0, 0));
        tFirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tFirstName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel2.add(tFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 230, 38));

        jLabel10.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Employee Id");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 138, 40));

        jLabel11.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Username");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 138, 40));

        tUsername.setBackground(new java.awt.Color(255, 255, 255));
        tUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tUsername.setForeground(new java.awt.Color(0, 0, 0));
        tUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel2.add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 230, 38));

        tEmployeeId.setBackground(new java.awt.Color(255, 255, 255));
        tEmployeeId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tEmployeeId.setForeground(new java.awt.Color(0, 0, 0));
        tEmployeeId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tEmployeeId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel2.add(tEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 230, 38));

        jLabel12.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Password");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 138, 40));

        tPassword.setBackground(new java.awt.Color(255, 255, 255));
        tPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tPassword.setForeground(new java.awt.Color(0, 0, 0));
        tPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel2.add(tPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 230, 38));

        jLabel13.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("First Name");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 138, 40));

        jLabel2.setFont(new java.awt.Font("Thibus29STru", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register New User");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkbox.setFont(new java.awt.Font("Thibus29STru", 1, 14)); // NOI18N
        checkbox.setForeground(new java.awt.Color(0, 0, 0));
        checkbox.setText("Show Password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 140, 30));

        jLabel3.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 138, 40));

        tRPassword.setBackground(new java.awt.Color(255, 255, 255));
        tRPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tRPassword.setForeground(new java.awt.Color(0, 0, 0));
        tRPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tRPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        tRPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(tRPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 230, 40));

        tREmployeeId.setBackground(new java.awt.Color(255, 255, 255));
        tREmployeeId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tREmployeeId.setForeground(new java.awt.Color(0, 0, 0));
        tREmployeeId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tREmployeeId.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel1.add(tREmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 230, 38));

        jLabel4.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Employee Id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 138, 40));

        jLabel9.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Enter Register User's Details");

        jLabel14.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Enter New User Details here");

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Cancel");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setFont(new java.awt.Font("Thibus29STru", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Register");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int YesNo = JOptionPane.showConfirmDialog(this,"Do you Want to Exit?","Exit",JOptionPane.YES_NO_OPTION);

        if(YesNo== JOptionPane.YES_OPTION){
            new login().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Retrieve input values
        String firstName = tFirstName.getText();
        String lastName = tLastName.getText();
        String employeeId = tEmployeeId.getText();
        String username = tUsername.getText();
        String password = tPassword.getText();
        String regEmployeeId = tREmployeeId.getText();
        String regPassword = tRPassword.getText();

        String checkEmployeeIdQuery = "SELECT employeeId FROM users WHERE employeeId = ?";
        String checkCredentialsQuery = "SELECT EmployeeID, Password FROM users WHERE Employeeid = ? AND Password = ?";

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection connection = DriverManager.getConnection(url, user, databasepassword);

            PreparedStatement checkEmployeeIdStmt = connection.prepareStatement(checkEmployeeIdQuery);
            checkEmployeeIdStmt.setString(1, employeeId);
            ResultSet result = checkEmployeeIdStmt.executeQuery();

            PreparedStatement checkCredentialsStmt = connection.prepareStatement(checkCredentialsQuery);
            checkCredentialsStmt.setString(1, regEmployeeId);
            checkCredentialsStmt.setString(2, regPassword);
            ResultSet result2 = checkCredentialsStmt.executeQuery();

            if (result.next()) {
                JOptionPane.showMessageDialog(rootPane, "Please change the Employee ID because " + employeeId + " exists with another user.");
            } else {

                if (firstName.isEmpty() || lastName.isEmpty() || employeeId.isEmpty() || username.isEmpty() || password.isEmpty() || regEmployeeId.isEmpty() || regPassword.isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Please fill all fields.");
                } else if (!result2.next()) {

                    JOptionPane.showMessageDialog(rootPane, "Registered User's Employee ID and password do not match. Please try again.");
                } else {

                    String sql = "insert into users (EmployeeId,Name,Username,Password,Registered_by) values(?,?,?,?,?)" ;

                    try (Connection conn = DriverManager.getConnection(url, user, databasepassword);

                        PreparedStatement pstmt = conn.prepareStatement(sql)) {

                        String FullName = firstName + " " + lastName;
                        pstmt.setString(1, employeeId);
                        pstmt.setString(2,FullName );
                        pstmt.setString(3,username);
                        pstmt.setString(4,password);
                        pstmt.setString(5,regEmployeeId);

                        pstmt.executeUpdate();

                        JOptionPane.showMessageDialog(rootPane,"Registration is Successfull.\nThis is Registered by" + regEmployeeId);
                        new login().setVisible(true);
                        this.dispose();

                    } catch (SQLException e) {
                        System.out.println("Error updating record: " + e.getMessage());
                    }

                }
            }

            result.close();
            result2.close();
            checkEmployeeIdStmt.close();
            checkCredentialsStmt.close();
            connection.close();

        } catch (SQLException e) {
            System.out.println("Error updating record: " + e.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void tRPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRPasswordActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        // TODO add your handling code here:

        if(checkbox.isSelected()){
            tRPassword.setEchoChar((char)0);
        }
        else{
            tRPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tEmployeeId;
    private javax.swing.JTextField tFirstName;
    private javax.swing.JTextField tLastName;
    private javax.swing.JTextField tPassword;
    private javax.swing.JTextField tREmployeeId;
    private javax.swing.JPasswordField tRPassword;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
